// ========== 地区数据库 (独立维护) ==========
// 寄递方式限制配置
// disabledMethods 可选值: "air" (航空), "sal" (SAL), "surface" (水陆路)
const deliveryRestrictions = {
    // 内陆国（无水陆路服务）
    "蒙古国": ["surface"], "哈萨克斯坦": ["surface"], "吉尔吉斯斯坦": ["surface"],
    "塔吉克斯坦": ["surface"], "乌兹别克斯坦": ["surface"], "土库曼斯坦": ["surface"],
    "阿富汗": ["surface"], "尼泊尔": ["surface"], "不丹": ["surface"], "老挝": ["surface"],
    "玻利维亚": ["surface"], "巴拉圭": ["surface"], "白俄罗斯": ["surface"], "捷克": ["surface"],
    "斯洛伐克": ["surface"], "匈牙利": ["surface"], "奥地利": ["surface"], "瑞士": ["surface"],
    "卢森堡": ["surface"], "塞尔维亚": ["surface"], "北马其顿": ["surface"], "摩尔多瓦": ["surface"],
    "阿塞拜疆": ["surface"], "亚美尼亚": ["surface"],
    // 岛国（无水陆路）
    "马尔代夫": ["surface"], "斐济": ["surface"], "汤加": ["surface"], "瓦努阿图": ["surface"],
    "萨摩亚": ["surface"], "基里巴斯": ["surface"], "图瓦卢": ["surface"], "马绍尔群岛": ["surface"],
    "帕劳": ["surface"], "密克罗尼西亚": ["surface"], "瑙鲁": ["surface"], "所罗门群岛": ["surface"],
    "巴布亚新几内亚": ["surface"], "塞舌尔": ["surface"], "科摩罗": ["surface"], "圣多美和普林西比": ["surface"],
    // 无SAL服务
    "冰岛": ["sal"], "格陵兰": ["sal"], "法罗群岛": ["sal"], "安道尔": ["sal"],
    "摩纳哥": ["sal"], "圣马力诺": ["sal"], "梵蒂冈": ["sal"], "列支敦士登": ["sal"],
    "马耳他": ["sal"], "塞浦路斯": ["sal"], "百慕大": ["sal"], "开曼群岛": ["sal"],
    // 高风险地区
    //"叙利亚": ["air", "sal"], "也门": ["air", "sal"], "索马里": ["air", "sal"],
    //"伊拉克": ["air"], "利比亚": ["air", "sal"], 
};

// 原始地区数据
const regionsRaw = [
    // 港澳台地区
    { name: "香港特别行政区", type: "hkmt" },
    { name: "澳门特别行政区", type: "hkmt" },
    { name: "台湾地区", type: "hkmt" },
    // 航空第一组
    { name: "朝鲜", type: "international", airGroup: 1, salGroup: 2, isSpecialSurface: false },
    { name: "蒙古国", type: "international", airGroup: 1, salGroup: 2, isSpecialSurface: false },
    { name: "越南", type: "international", airGroup: 1, salGroup: 2, isSpecialSurface: true },
    { name: "日本", type: "international", airGroup: 1, salGroup: 1, isSpecialSurface: true },
    { name: "韩国", type: "international", airGroup: 1, salGroup: 1, isSpecialSurface: true },
    { name: "哈萨克斯坦", type: "international", airGroup: 1, salGroup: 2, isSpecialSurface: false },
    { name: "吉尔吉斯斯坦", type: "international", airGroup: 1, salGroup: 2, isSpecialSurface: false },
    { name: "塔吉克斯坦", type: "international", airGroup: 1, salGroup: 2, isSpecialSurface: false },
    { name: "乌兹别克斯坦", type: "international", airGroup: 1, salGroup: 2, isSpecialSurface: false },
    { name: "土库曼斯坦", type: "international", airGroup: 1, salGroup: 2, isSpecialSurface: false },
    // 航空第二组
    { name: "阿联酋", type: "international", airGroup: 2, salGroup: 2, isSpecialSurface: true },
    { name: "阿曼", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: false },
    { name: "巴基斯坦", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "巴林", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: false },
    { name: "菲律宾", type: "international", airGroup: 2, salGroup: 2, isSpecialSurface: true },
    { name: "格鲁吉亚", type: "international", airGroup: 2, salGroup: 1, isSpecialSurface: false },
    { name: "柬埔寨", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "卡塔尔", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: false },
    { name: "科威特", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: false },
    { name: "老挝", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "马尔代夫", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "马来西亚", type: "international", airGroup: 2, salGroup: 2, isSpecialSurface: true },
    { name: "孟加拉国", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "缅甸", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "尼泊尔", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "斯里兰卡", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "泰国", type: "international", airGroup: 2, salGroup: 2, isSpecialSurface: true },
    { name: "文莱", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "新加坡", type: "international", airGroup: 2, salGroup: 2, isSpecialSurface: true },
    { name: "印度", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    { name: "印度尼西亚", type: "international", airGroup: 2, salGroup: 3, isSpecialSurface: true },
    // 航空第三组
    { name: "阿塞拜疆", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "土耳其", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "伊拉克", type: "international", airGroup: 3, salGroup: 3, isSpecialSurface: false },
    { name: "约旦", type: "international", airGroup: 3, salGroup: 3, isSpecialSurface: false },
    { name: "阿尔巴尼亚", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "爱尔兰", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "爱沙尼亚", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "奥地利", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "白俄罗斯", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "保加利亚", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "比利时", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "冰岛", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "波兰", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "丹麦", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "德国", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "法国", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "芬兰", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "荷兰", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "捷克", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "克罗地亚", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "拉脱维亚", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "立陶宛", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "卢森堡", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "罗马尼亚", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "马耳他", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "摩尔多瓦", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "挪威", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "葡萄牙", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "瑞典", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "塞尔维亚", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "斯洛伐克", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "斯洛文尼亚", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "乌克兰", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "西班牙", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "希腊", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "匈牙利", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "意大利", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "英国", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "加拿大", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "美国", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: false },
    { name: "澳大利亚", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: true },
    { name: "新西兰", type: "international", airGroup: 3, salGroup: 2, isSpecialSurface: true },
    { name: "加那利群岛(西班牙)", type: "international", airGroup: 3, salGroup: 3, isSpecialSurface: false },
    { name: "亚速尔群岛和马德拉群岛(葡萄牙)", type: "international", airGroup: 3, salGroup: 4, isSpecialSurface: false },
    // 航空第四组
    { name: "俄罗斯", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "塞浦路斯", type: "international", airGroup: 4, salGroup: 2, isSpecialSurface: false },
    { name: "亚美尼亚", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "安道尔", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "波斯尼亚和黑塞哥维那(波黑)", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "法罗群岛", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "直布罗陀", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "梵蒂冈", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "黑山", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "列支敦士登", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "北马其顿", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "摩纳哥", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "瑞士", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "圣马力诺", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "阿富汗", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: true },
    { name: "不丹", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: true },
    { name: "斐济", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: true },
    { name: "伊朗", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: false },
    { name: "瑙鲁", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: true },
    { name: "巴布亚新几内亚", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: true },
    { name: "所罗门群岛", type: "international", airGroup: 4, salGroup: 3, isSpecialSurface: true },
    { name: "科摩罗", type: "international", airGroup: 4, salGroup: 4, isSpecialSurface: false },
    { name: "圣多美和普林西比", type: "international", airGroup: 4, salGroup: 4, isSpecialSurface: false },
    { name: "莱索托", type: "international", airGroup: 4, salGroup: 4, isSpecialSurface: false },
    { name: "巴西", type: "international", airGroup: 4, salGroup: 4, isSpecialSurface: false },
    { name: "玻利维亚", type: "international", airGroup: 4, salGroup: 4, isSpecialSurface: false },
    { name: "巴拉圭", type: "international", airGroup: 4, salGroup: 4, isSpecialSurface: false }
];

// 为每个地区添加限制字段，生成最终数据
const regionsData = regionsRaw.map(region => ({
    ...region,
    disabledMethods: deliveryRestrictions[region.name] || []
}));